// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 1);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "EG");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"8000df83-12bd-447f-ac3c-3e8105d8b4e5\",\"default-theme@mozilla.org\":\"202b4b96-e0fa-4250-b7d4-b075f9a3c3da\",\"google@search.mozilla.org\":\"0f271455-5ad9-4430-b832-bdbea531ffad\",\"amazondotcom@search.mozilla.org\":\"488b87d1-6789-4841-9e52-ea8b7bb621ef\",\"bing@search.mozilla.org\":\"f0451713-2fb3-45b7-93f8-75f527a45b70\",\"ddg@search.mozilla.org\":\"9a3fd05c-e444-49db-b3f9-2870d37d2c88\",\"twitter@search.mozilla.org\":\"5d338311-9d37-4927-9829-d728d8016661\",\"wikipedia@search.mozilla.org\":\"62a560db-b9e3-4df5-b45a-718511accba3\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "8ed30b35-870b-4f90-b29d-7a2628fd3d7");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("security.sandbox.plugin.tempDirSuffix", "c116d49f-fe0f-40e0-b67f-a74d0a556fd5");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.prompted", 2);
